mysite/hackthe6ix/urls.py
from django.urls import path

from . import views

app_name = 'hackthe6ix'
urlpatterns = [
    path('', views.index, name='index'),
    path('registration/', views.registration, name="register"),
    path('login/', views.index, name="login"),
    path('verify/', views.verify, name="verify"),
    path('profile/', views.profile, name="profile"),
    path('listform/', views.listform, name='listform'),
    path('map.html', views.map, name='map'),
    path('heremap.html', views.heremap, name='heremap'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hackthe6ix.urls'))
]

mysite/hackthe6ix/models.py
from django.db import models

# Create your models here.

class Person(models.Model):
    id = models.AutoField(primary_key=True)
    email = models.CharField(max_length=50, default="dummy")
    password = models.CharField(max_length=30, default="dummy")
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    age = models.IntegerField(default=3)
    gender = models.CharField(max_length=10, default="dummy")
    profilepic = models.CharField(max_length=70, default="dummy")

class Listings(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE, default=None)
    address = models.CharField(max_length=30)
    price = models.IntegerField(default=40)
    gender = models.CharField(max_length=10, default="dummy")
    lease = models.PositiveIntegerField(default=600)
    phone = models.CharField(max_length=20, default="dummy")
    propertypic = models.CharField(max_length=70, default="dummy")
    description = models.CharField(max_length=300, default="dummy")

class Landlord(models.Model):
	pass
    # pId = models.ForeignKey(Person, on_delete=models.CASCADE)

class Tenants(models.Model):
	pass
    # pId = models.ForeignKey(Person, on_delete=models.CASCADE)

mysite/hackthe6ix/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Person, Listings
from .listing import getList

userUID = 0
loggedIn = False

# Create your views here.
def index(request):
	try:
		global userUID
		global loggedIn
		# when user logs in with correct password
		person = Person.objects.get(email=request.POST['username'],password=request.POST['pass'])
		if person :
			userUID = person.id
			loggedIn = True
			return render(request, 'hackthe6ix/index.html', {'data':getList()})
	except Exception as e:
		try:
			# when seller submits a form.
			user = Person.objects.get(pk=userUID)
			listForm = Listings.objects.create(person=user, address = request.POST['address'], gender = request.POST['gender'],
								price = request.POST['price'], phone = request.POST['phone'],
								propertypic = request.POST['propertypic'], lease = request.POST['lease'], description=request.POST['description'])
			listForm.save()

			return render(request, 'hackthe6ix/index.html', {'data':getList()})
		except Exception as e:
			print(e)
	if loggedIn:
		return render(request, 'hackthe6ix/index.html', {'data':getList()})

	return render(request, 'hackthe6ix/login.html')

def registration(request):
	return render(request, 'hackthe6ix/registration.html')

def verify(request):
	email = request.POST['email']
	password = request.POST['password']

	try:
		if Person.objects.get(email = email):
			return render(request, 'hackthe6ix/registration.html')
	except Exception:
		pass
	person = Person(email = email, password = password, 
					first_name = request.POST['first_name'], last_name = request.POST['last_name'],
				    age = request.POST['age'], gender = request.POST['gender'], profilepic = request.POST['profilepic'])
	person.save()
	return render(request, 'hackthe6ix/verify.html')

def map(request):
	return render(request, 'hackthe6ix/map.html')
<<<<<<< HEAD
=======

def profile(request):
	return render(request, 'hackthe6ix/profile.html')

def listform(request):
	return render(request, 'hackthe6ix/listform.html')
	
def heremap(request):
	return render(request, 'hackthe6ix/heremap.html')
	
>>>>>>> 903f47ac56e7a76147294bfa17b57abd69a1f44a

mysite/hackthe6ix/templates/hackthe6ix/listform.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Registration Form</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
  
      <link rel='stylesheet' href='https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0-rc3/angular-material.css'>
    <link rel='stylesheet' href='http://localhost:8080/docs.css'>

      <link rel="stylesheet" href="{% static 'hackthe6ix/css/style.css' %}">

  
</head>

<body>

  <div ng-controller="DemoCtrl" ng-cloak="" class="md-inline-form" ng-app="MyApp" layout="column" layout-sm="row" layout-align="center center" layout-align-sm="start start" layout-fill>
		<md-content id="SignupContent" class="md-whiteframe-10dp" flex-sm>
				<md-toolbar flex id="materialToolbar">
						<div class="md-toolbar-tools"> <span flex=""></span> <span class="md-headline" align="center">Sell Residence</span> <span flex=""></span> </div>
				</md-toolbar>
				<div layout-padding="">
						<div></div>
						<form name="userForm" method="POST" action="{% url 'hackthe6ix:index' %}" ng-submit="user.submit(userForm.$valid)" enctype="multipart/form-data">
                {% csrf_token %}
								<input type="hidden" name="action" value="signup" />
								<div layout="row" layout-sm="column">
										<md-input-container flex-gt-sm="">
												<label>Address</label>
												<input ng-model="user.address" name="address" required type="text" placeholder="Your Address">
												<div ng-if="userForm.address.$dirty" ng-messages="userForm.address.$error" role="alert">
														<div ng-message="required" class="my-message">Address is Required.</div>
														<div ng-message="pattern" class="my-message">Enter correct Address.</div>
												</div>
										</md-input-container>
								</div>
								<div layout="row" layout-sm="column">
									<p style="font-size: 12px; margin-left: 3px; margin-top: 18px;">Gender: </p>
				                   <div layout="row" layout-sm="column">
				                    <md-input-container   flex-gt-sm="">
				                        <input required type="gender" name="gender" ng-model="user.gender" placeholder="M/F" />
				                        <div ng-if="userForm.gender.$dirty" ng-messages="userForm.gender.$error" role="alert">
				                            <div ng-message="required" class="my-message">Gender is Required.</div>
				                            <div ng-message="pattern" class="my-message">Enter Correct Gender. </div>
				                            <div ng-message="gender" class="my-message">Enter Correct Gender. </div>
				                        </div>
				                    </md-input-container>
				                </div>
								<div layout="row" layout-sm="column">
										<md-input-container flex-gt-sm="">
												<label>Phone Number</label>
												<input required type="phone" name="phone" ng-model="user.phone" placeholder="647-234-1234" />
												<div ng-if="userForm.phone.$dirty" ng-messages="userForm.phone.$error" role="alert">
														<div ng-message="required" class="my-message">Phone Number is Required.</div>
														<div ng-message="pattern" class="my-message">Enter Correct Phone Number. </div>
														<div ng-message="phone" class="my-message">Enter Correct Phone Number. </div>
												</div>
										</md-input-container>
								</div>
								<div layout="row" layout-sm="column">
										<md-input-container flex-gt-sm="">
												<label>Price / Month</label>
												<input required type="price" name="price" ng-model="user.price" placeholder="600" />
												<div ng-if="userForm.price.$dirty" ng-messages="userForm.price.$error" role="alert">
														<div ng-message="required" class="my-message">Price is Required.</div>
														<div ng-message="pattern" class="my-message">Enter Correct Price. </div>
														<div ng-message="price" class="my-message">Enter Correct Price. </div>
												</div>
										</md-input-container>
								</div>
								<div layout="row" layout-sm="column">
										<md-input-container flex-gt-sm="">
												<label>Lease Length (Months)</label>
												<input required type="lease" name="lease" ng-model="user.lease" placeholder="4" />
												<div ng-if="userForm.lease.$dirty" ng-messages="userForm.lease.$error" role="alert">
														<div ng-message="required" class="my-message">Lease Length is Required.</div>
														<div ng-message="pattern" class="my-message">Enter Correct Lease Length. </div>
														<div ng-message="lease" class="my-message">Enter Correct Lease Length. </div>
												</div>
										</md-input-container>
								</div>
																	<md-input-container flex-gt-sm="">
												<label>Description</label>
												<input ng-model="user.description" name="description" required type="text" placeholder="Description">
												<div ng-if="userForm.description.$dirty" ng-messages="userForm.description.$error" role="alert">
														<div ng-message="required" class="my-message">Description is Required.</div>
														<div ng-message="pattern" class="my-message">Enter correct Description.</div>
												</div>
										</md-input-container>
                                <div layout="row" layout-sm="column">
                    <md-input-container flex-gt-sm="">
                        <label>Property Picture</label>
                        <input required type="imgurlink" name="propertypic" ng-model="user.propertypic" placeholder="https://i.imgur.com/nhva7tO.jpg" />
                        <div ng-if="userForm.propertypic.$dirty" ng-messages="userForm.propertypic.$error" role="alert">
                            <div ng-message="required" class="my-message">Property Picture is Required.</div>
                        </div>
                    </md-input-container>
                </div>
								<md-button class="md-raised md-primary" style="width:100%; margin: 0px 0px;" type="submit" ng-disabled="userForm.$invalid" name="submit" onclick="closeIFrame()">Post</md-button>
								<!--<md-button class="md-raised md-primary" ng-href="https://codepen.io/faizanrupani/pen/QjzMJp" target="_blank" style="width:100%; margin: 15px 0px 0px 0px;">Code Pen Login Form</md-button>-->
						</form>
				</div>
		</md-content>
</div>
  <script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular.js'></script>
<script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-animate.min.js'></script>
<script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-route.min.js'></script>
<script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-aria.min.js'></script>
<script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-messages.min.js'></script>
<script src='https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0-rc3/angular-material.js'></script>
<script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-114/assets-cache.js'></script>
<script  src="{% static 'hackthe6ix/js/index.js'%}"></script>
<script src="{% static 'hackthe6ix/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript">
	function closeIFrame() {
		parent.$.fancybox.close();
	}
</script>




</body>

</html>

mysite/hackthe6ix/templates/hackthe6ix/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'hackthe6ix/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	<div class="container-login100" style="background-image: url('../../static/hackthe6ix/images/housing.jpg');">
		<div class="wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30">
			<form class="login100-form validate-form" action="{% url 'hackthe6ix:login' %}" method="POST">
				{% csrf_token %}
				<span class="login100-form-title p-b-37">
					Sign In
				</span>

				<div class="wrap-input100 validate-input m-b-20" data-validate="Enter email">
					<input class="input100" type="text" name="username" placeholder="email">
					<span class="focus-input100"></span>
				</div>

				<div class="wrap-input100 validate-input m-b-25" data-validate = "Enter password">
					<input class="input100" type="password" name="pass" placeholder="password">
					<span class="focus-input100"></span>
				</div>

				<div class="container-login100-form-btn">
					<button class="login100-form-btn">
						Sign In
					</button>
				</div>
<!--
				<div class="text-center p-t-57 p-b-20">
					<span class="txt1">
						Or login with
					</span>
				</div>

				<div class="flex-c p-b-112">
					<a href="#" class="login100-social-item">
						<i class="fa fa-facebook-f"></i>
					</a>

					<a href="#" class="login100-social-item">
						<img src="images/icons/icon-google.png" alt="GOOGLE">
					</a>
				</div>
			-->

				<div class="text-center" id="dialog_trigger">
					<a class="iframe" href="{% url 'hackthe6ix:register' %}" class="txt2 hov1" id="dummy">
							Sign Up
					</a>	
				</div>
			</form>

			
		</div>
	</div>
	
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'hackthe6ix/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'hackthe6ix/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'hackthe6ix/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'hackthe6ix/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'hackthe6ix/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'hackthe6ix/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'hackthe6ix/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'hackthe6ix/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'hackthe6ix/js/main.js' %}"></script>
	<script src="{% static 'hackthe6ix/js/login.js' %}"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.7/angular-route.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
	<script type="text/javascript" src="{% static 'hackthe6ix/js/jquery.fancybox-1.3.4/fancybox/jquery.fancybox-1.3.4.pack.js' %}"></script>
	<link rel="stylesheet" href="{% static 'hackthe6ix/js/jquery.fancybox-1.3.4/fancybox/jquery.fancybox-1.3.4.css' %}" type="text/css" media="screen" />
	<script type="text/javascript">
		$(document).ready(function() {

	/* This is basic - uses default settings */
	
	$("a#dummy").fancybox({
		'width':615,
		'height':800
	});
	
});
	</script>

</body>
</html>

mysite/hackthe6ix/templates/hackthe6ix/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en" >

<head>
  <meta charset="UTF-8">
  <title>Registration Form</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">
  
      <link rel='stylesheet' href='https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0-rc3/angular-material.css'>
    <link rel='stylesheet' href='http://localhost:8080/docs.css'>

      <link rel="stylesheet" href="{% static 'hackthe6ix/css/style.css' %}">

  
</head>

<body>

  <div ng-controller="DemoCtrl" ng-cloak="" class="md-inline-form" ng-app="MyApp" layout="column" layout-sm="row" layout-align="center center" layout-align-sm="start start" layout-fill>
		<md-content id="SignupContent" class="md-whiteframe-10dp" flex-sm>
				<md-toolbar flex id="materialToolbar">
						<div class="md-toolbar-tools"> <span flex=""></span> <span class="md-headline" align="center">Registration Form</span> <span flex=""></span> </div>
				</md-toolbar>
				<div layout-padding="">
						<div></div>
						<form name="userForm" method="POST" action="{% url 'hackthe6ix:verify' %}" ng-submit="user.submit(userForm.$valid)" enctype="multipart/form-data">
                {% csrf_token %}
								<input type="hidden" name="action" value="signup" />
								<div layout="row" layout-sm="column">
										<md-input-container flex-gt-sm="">
												<label>First name</label>
												<input ng-model="user.first_name" name="first_name" required type="text" ng-pattern="/^[a-zA-Z'. -]+$/" placeholder="Your First Name">
												<div ng-if="userForm.first_name.$dirty" ng-messages="userForm.first_name.$error" role="alert">
														<div ng-message="required" class="my-message">First Name is Required.</div>
														<div ng-message="pattern" class="my-message">Enter correct First Name.</div>
												</div>
										</md-input-container>
										<md-input-container flex-gt-sm="">
												<label>Last Name</label>
												<input ng-model="user.last_name" name="last_name" required type="text" ng-pattern="/^[a-zA-Z'. -]+$/" placeholder="Your Last Name">
												<div ng-if="userForm.last_name.$dirty" ng-messages="userForm.last_name.$error" role="alert">
														<div ng-message="required" class="my-message">Last Name is Required.</div>
														<div ng-message="pattern" class="my-message">Enter correct Last Name.</div>
												</div>
										</md-input-container>
								</div>
								<div layout="row" layout-sm="column">
										<p style="font-size: 12px; margin-left: 3px; margin-top: 18px;">Gender: </p>
                   <div layout="row" layout-sm="column">
                    <md-input-container   flex-gt-sm="">
                        <input required type="gender" name="gender" ng-model="user.gender" placeholder="M/F" />
                        <div ng-if="userForm.gender.$dirty" ng-messages="userForm.gender.$error" role="alert">
                            <div ng-message="required" class="my-message">Gender is Required.</div>
                            <div ng-message="pattern" class="my-message">Enter Correct Gender. </div>
                            <div ng-message="gender" class="my-message">Enter Correct Gender. </div>
                        </div>
                    </md-input-container>
                </div>
										<md-input-container flex-gt-sm="60">
												<label>Age</label>
												<input required type="number" step="any" name="age" ng-model="user.age" min="13" max="100" placeholder="20" />
										</md-input-container>
								</div>
								<div layout="row" layout-sm="column">
										<md-input-container   flex-gt-sm="">
												<label>Email</label>
												<input required type="email" name="email" ng-model="user.email" ng-pattern="/^[_a-z0-9-+]+(\.[_a-z0-9-+]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/" placeholder="someone@example.com" />
												<div ng-if="userForm.email.$dirty" ng-messages="userForm.email.$error" role="alert">
														<div ng-message="required" class="my-message">Email Address is Required.</div>
														<div ng-message="pattern" class="my-message">Enter Correct Email Address. </div>
														<div ng-message="email" class="my-message">Enter Correct Email Address. </div>
												</div>
										</md-input-container>
								</div>
								<div layout="row" layout-sm="column">
										<md-input-container flex-gt-sm="">
												<label>New Password</label>
												<input name="password" ng-model="user.password" type="password" minlength="8" maxlength="100" ng-pattern="/(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}/" required placeholder="********">
												<div ng-if="userForm.password.$dirty" ng-messages="userForm.password.$error" role="alert" multiple>
														<div ng-message="required">Password is Required.</div>
														<div ng-message="pattern">Password should contain at least one number, one lowercase and one uppercase character.</div>
														<div ng-message="minlength">Password should be greater than 8 letters.</div>
														<div ng-message="maxlength">Password Can't be more than 100 letters.</div>
												</div>
										</md-input-container>
										<md-input-container flex-gt-sm="">
												<label>Confirm Password</label>
												<input name="confmPassword" ng-model="user.confmPassword" type="password" minlength="8" maxlength="100" ng-pattern="/(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}/" required compare-to="user.password" placeholder="********">
												<div ng-if="userForm.confmPassword.$dirty" ng-messages="userForm.confmPassword.$error" role="alert">
														<div ng-message="required">Confirm Password is Required.</div>
														<div ng-message="compareTo">Password Doesn't Match.</div>
												</div>
										</md-input-container>
								</div>
                                <div layout="row" layout-sm="column">
                    <md-input-container flex-gt-sm="">
                        <label>Profile Picture</label>
                        <input required type="imgurlink" name="profilepic" ng-model="user.profilepic" placeholder="https://i.imgur.com/nhva7tO.jpg" />
                        <div ng-if="userForm.profilepic.$dirty" ng-messages="userForm.profilepic.$error" role="alert">
                            <div ng-message="required" class="my-message">Email Address is Required.</div>
                        </div>
                    </md-input-container>
                </div>
								<md-button class="md-raised md-primary" style="width:100%; margin: 0px 0px;" type="submit" ng-disabled="userForm.$invalid" name="submit" onclick="closeIFrame()">Submit</md-button>
								<!--<md-button class="md-raised md-primary" ng-href="https://codepen.io/faizanrupani/pen/QjzMJp" target="_blank" style="width:100%; margin: 15px 0px 0px 0px;">Code Pen Login Form</md-button>-->
						</form>
				</div>
		</md-content>
</div>
  <script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular.js'></script>
<script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-animate.min.js'></script>
<script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-route.min.js'></script>
<script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-aria.min.js'></script>
<script src='https://ajax.googleapis.com/ajax/libs/angularjs/1.4.6/angular-messages.min.js'></script>
<script src='https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0-rc3/angular-material.js'></script>
<script src='https://s3-us-west-2.amazonaws.com/s.cdpn.io/t-114/assets-cache.js'></script>
<script  src="{% static 'hackthe6ix/js/index.js'%}"></script>
<script src="{% static 'hackthe6ix/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript">
  function closeIFrame() {
    parent.$.fancybox.close();
  }
</script>



</body>

</html>

mysite/hackthe6ix/templates/hackthe6ix/verify.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V9</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'hackthe6ix/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,400italic">

<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'hackthe6ix/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	
	<div class="container-login100" style="background-image: url('../../static/hackthe6ix/images/housing.jpg');">
		<div class="wrap-login100">
			<span class="login100-form-title p-b-37">
			<br>Thank You!<br> Please check your email to activate your account! <br> <a href="{%url 'hackthe6ix:login'%}"> click here to go back to login </a>
			</span>
		</div>
	</div>
	
	

	<div id="dropDownSelect1"></div>
	
<!--===============================================================================================-->
	<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'js/main.js' %}"></script>

</body>
</html>